### ISSUE TITLE
Use twitch2tuner with Emby via docker-compose

### ISSUE THREAD

**Issue by tuprimafromtomelloso** [micahmo/twitch2tuner#6]
Thanks for you work. A quick questions.

1. Since this is a HDHomerun emulation, it will work with emby? 

YES, it works!

2. Can i install it via docker-compose from a .yml file in a VPS and then connect it to my local server or its only working in local? 

YES, you can.

``` yaml
version: '3.2'

services:
  twitch2tuner:
    container_name: twitch2tuner
    image: ghcr.io/micahmo/twitch2tuner:latest
    expose:
      - 22708
    ports:
      - "22708:22708"
    environment:      
      - CLIENT_ID=X
      - CLIENT_SECRET=X
      - TWITCH_USERNAME=X
      - USE_PROFILE_AS_JUST_CHATTING=true
    restart: unless-stopped
```

with that docker-compose.yml runs like a charm! thank you for your work!
